// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID         string `json:"id"`
	Userid     string `json:"userid"`
	Like       int    `json:"like"`
	Disilike   int    `json:"disilike"`
	Replyto    int    `json:"replyto"`
	Desc       string `json:"desc"`
	Videoid    int    `json:"videoid"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
	Replycount int    `json:"replycount"`
	Postid     int    `json:"postid"`
}

type Link struct {
	ID     string `json:"id"`
	Label  string `json:"label"`
	URL    string `json:"url"`
	Userid string `json:"userid"`
}

type Notification struct {
	ID     string `json:"id"`
	Userid string `json:"userid"`
	Vidthm string `json:"vidthm"`
	Title  string `json:"title"`
}

type Playlist struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Userid     string `json:"userid"`
	Visibility string `json:"visibility"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
	View       int    `json:"view"`
	Desc       string `json:"desc"`
	Videos     string `json:"videos"`
}

type Post struct {
	ID         string `json:"id"`
	Userid     string `json:"userid"`
	Like       int    `json:"like"`
	Disilike   int    `json:"disilike"`
	Desc       string `json:"desc"`
	Attachment string `json:"attachment"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
}

type User struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Profilepic        string `json:"profilepic"`
	Premium           string `json:"premium"`
	Likedvideos       string `json:"likedvideos"`
	Disilikedvideos   string `json:"disilikedvideos"`
	Likedcomments     string `json:"likedcomments"`
	Disilikedcomments string `json:"disilikedcomments"`
	Subscribed        string `json:"subscribed"`
	Subscribers       int    `json:"subscribers"`
	Likedpost         string `json:"likedpost"`
	Disilikedpost     string `json:"disilikedpost"`
	About             string `json:"about"`
	Channelart        string `json:"channelart"`
	Day               int    `json:"day"`
	Month             int    `json:"month"`
	Year              int    `json:"year"`
	Premiday          int    `json:"premiday"`
	Premimonth        int    `json:"premimonth"`
	Premiyear         int    `json:"premiyear"`
	Premitype         string `json:"premitype"`
	Archivedplaylists string `json:"archivedplaylists"`
}

type Video struct {
	ID          string `json:"id"`
	URL         string `json:"url"`
	Title       string `json:"title"`
	Thumbnail   string `json:"thumbnail"`
	Restriction string `json:"restriction"`
	Desc        string `json:"desc"`
	Category    string `json:"category"`
	Visibility  string `json:"visibility"`
	Location    string `json:"location"`
	Userid      string `json:"userid"`
	Like        int    `json:"like"`
	Disilike    int    `json:"disilike"`
	View        int    `json:"view"`
	Channelpic  string `json:"channelpic"`
	Channelname string `json:"channelname"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Duration    int    `json:"duration"`
	Premium     string `json:"premium"`
}

type AddToPlaylist struct {
	Videos string `json:"videos"`
}

type NewComment struct {
	Userid     string `json:"userid"`
	Like       int    `json:"like"`
	Disilike   int    `json:"disilike"`
	Replyto    int    `json:"replyto"`
	Desc       string `json:"desc"`
	Videoid    int    `json:"videoid"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
	Replycount int    `json:"replycount"`
	Postid     int    `json:"postid"`
}

type NewLink struct {
	Label  string `json:"label"`
	URL    string `json:"url"`
	Userid string `json:"userid"`
}

type NewNotification struct {
	Userid string `json:"userid"`
	Vidthm string `json:"vidthm"`
	Title  string `json:"title"`
}

type NewPlaylist struct {
	Title      string `json:"title"`
	Userid     string `json:"userid"`
	Visibility string `json:"visibility"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
	View       int    `json:"view"`
	Desc       string `json:"desc"`
	Videos     string `json:"videos"`
}

type NewPost struct {
	Userid     string `json:"userid"`
	Like       int    `json:"like"`
	Disilike   int    `json:"disilike"`
	Desc       string `json:"desc"`
	Attachment string `json:"attachment"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
}

type NewUser struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Profilepic        string `json:"profilepic"`
	Premium           string `json:"premium"`
	Likedvideos       string `json:"likedvideos"`
	Disilikedvideos   string `json:"disilikedvideos"`
	Likedcomments     string `json:"likedcomments"`
	Disilikedcomments string `json:"disilikedcomments"`
	Subscribed        string `json:"subscribed"`
	Subscribers       int    `json:"subscribers"`
	Likedpost         string `json:"likedpost"`
	Disilikedpost     string `json:"disilikedpost"`
	About             string `json:"about"`
	Channelart        string `json:"channelart"`
	Day               int    `json:"day"`
	Month             int    `json:"month"`
	Year              int    `json:"year"`
	Premiday          int    `json:"premiday"`
	Premimonth        int    `json:"premimonth"`
	Premiyear         int    `json:"premiyear"`
	Premitype         string `json:"premitype"`
	Archivedplaylists string `json:"archivedplaylists"`
}

type NewVideo struct {
	URL         string `json:"url"`
	Title       string `json:"title"`
	Thumbnail   string `json:"thumbnail"`
	Restriction string `json:"restriction"`
	Desc        string `json:"desc"`
	Category    string `json:"category"`
	Visibility  string `json:"visibility"`
	Location    string `json:"location"`
	Userid      string `json:"userid"`
	Like        int    `json:"like"`
	Disilike    int    `json:"disilike"`
	View        int    `json:"view"`
	Channelpic  string `json:"channelpic"`
	Channelname string `json:"channelname"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Duration    int    `json:"duration"`
	Premium     string `json:"premium"`
}
