// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Playlist struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Userid     string `json:"userid"`
	Visibility string `json:"visibility"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
	View       int    `json:"view"`
	Desc       string `json:"desc"`
	Videos     string `json:"videos"`
}

type User struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Profilepic string `json:"profilepic"`
	Premium    string `json:"premium"`
}

type Video struct {
	ID          string `json:"id"`
	URL         string `json:"url"`
	Title       string `json:"title"`
	Thumbnail   string `json:"thumbnail"`
	Restriction string `json:"restriction"`
	Desc        string `json:"desc"`
	Category    string `json:"category"`
	Playlist    string `json:"playlist"`
	Visibility  string `json:"visibility"`
	Location    string `json:"location"`
	Userid      string `json:"userid"`
	Like        int    `json:"like"`
	Disilike    int    `json:"disilike"`
	View        int    `json:"view"`
	Channelpic  string `json:"channelpic"`
	Channelname string `json:"channelname"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
}

type AddToPlaylist struct {
	Videos string `json:"videos"`
}

type NewPlaylist struct {
	Title      string `json:"title"`
	Userid     string `json:"userid"`
	Visibility string `json:"visibility"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
	View       int    `json:"view"`
	Desc       string `json:"desc"`
	Videos     string `json:"videos"`
}

type NewUser struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Profilepic string `json:"profilepic"`
	Premium    string `json:"premium"`
}

type NewVideo struct {
	URL         string `json:"url"`
	Title       string `json:"title"`
	Thumbnail   string `json:"thumbnail"`
	Restriction string `json:"restriction"`
	Desc        string `json:"desc"`
	Category    string `json:"category"`
	Playlist    string `json:"playlist"`
	Visibility  string `json:"visibility"`
	Location    string `json:"location"`
	Userid      string `json:"userid"`
	Like        int    `json:"like"`
	Disilike    int    `json:"disilike"`
	View        int    `json:"view"`
	Channelpic  string `json:"channelpic"`
	Channelname string `json:"channelname"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
}
